<a href="https://colab.research.google.com/github/asrianda/pemograman/blob/main/Algo_A5_Lat2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
#-- Mambaca dataset CSV
df=pd.read_csv('titanic_data.csv')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:
df['class'].value_counts()

class
Third     489
First     216
Second    184
Name: count, dtype: int64

In [14]:
#df.drop(columns=['pclass','embarked'], inplace=True)
df.head()

,survived,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone
0,0,male,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False
1,1,female,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False
2,1,female,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True
3,1,female,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False
4,0,male,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True

In [17]:
#-- Menghapus kolum yang tidak perlu --
df.drop(columns=['who','deck','embark_town','alone'], inplace=True)
df.head()

   survived     sex   age  sibsp  parch     fare  class  adult_male alive
0         0    male  22.0      1      0   7.2500  Third        True    no
1         1  female  38.0      1      0  71.2833  First       False   yes
2         1  female  26.0      0      0   7.9250  Third       False   yes
3         1  female  35.0      1      0  53.1000  First       False   yes
4         0    male  35.0      0      0   8.0500  Third        True    no

In [19]:
#-- data yang null di age diisi dengan rata-rata umur --
df['age'].fillna(df['age'].mean(), inplace=True)
df.head()

<ipython-input-19-f25f05b57f6c>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(), inplace=True)

   survived     sex   age  sibsp  parch     fare  class  adult_male alive
0         0    male  22.0      1      0   7.2500  Third        True    no
1         1  female  38.0      1      0  71.2833  First       False   yes
2         1  female  26.0      0      0   7.9250  Third       False   yes
3         1  female  35.0      1      0  53.1000  First       False   yes
4         0    male  35.0      0      0   8.0500  Third        True    no

In [3]:
#-- Melihat banyak data
df.shape

(889, 15)

In [20]:
df.isnull().sum()

survived      0
sex           0
age           0
sibsp         0
parch         0
fare          0
class         0
adult_male    0
alive         0
dtype: int64